org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.219
neo_version_range=[21,)

loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=craftersnpcanimations
mod_name=Crafters NPC Animations
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=org.crafterscr
mod_authors=RobertoImI1 - Crafters CR

mod_description=Motor de NPCs humanoides animados compatible con Crafters NPC y Emotecraft.